### ISSUE TITLE
java.lang.VerifyError when running on a simple Spring Boot Example

### ISSUE THREAD

**Issue by jon-bell** [MirrorTaint/MirrorTaint#1]
Hi,
I've attempted to follow the instructions provided to run MirrorTaint with a Spring Boot example project, and received a `java.lang.VerifyError`. The README is somewhat unclear of exactly how I should be attempting to run MirrorTaint, so please let me know if I should be doing any other steps when I run it. I've attached a zip of the jar file that I am running, and copy-pasted the output:

[bootproject3-0.0.1-SNAPSHOT.jar.zip](https://github.com/MirrorTaint/MirrorTaint/files/11533774/bootproject3-0.0.1-SNAPSHOT.jar.zip)

```
$ java -javaagent:/Users/jon/.m2/repository/com/mirror/taint/taint-agent-core/1.0.0/taint-agent-core-1.0.0.jar -jar ../bootproject3-0.0.1-SNAPSHOT.jar 
Premain invoked, version=20230522124848
Exception in thread "main" java.lang.VerifyError: Operand stack underflow
Exception Details:
  Location:
    org/springframework/boot/loader/jar/JarFile.<init>(Ljava/io/File;)V @249: dup
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @249
    flags: { }
    locals: { 'org/springframework/boot/loader/jar/JarFile', 'java/io/File', 'com/shadow/taint/agent/model/StackFrame', '[Ljava/lang/Object;', '[Ljava/lang/Object;' }
    stack: { }
  Bytecode:
    0x0000000: 1302 3abd 022a 4e2d 1302 3b2b 5313 023c
    0x0000010: 1302 3a13 023d 1302 3e13 023f 1302 3b2d
    0x0000020: b802 454d 1302 3abd 022a 3a04 2a2c 1302
    0x0000030: 4613 023b b602 4abb 00cd 2c13 024b 1302
    0x0000040: 4cb6 0250 592c 1302 51b6 0255 2b2c 1302
    0x0000050: 4613 023a b602 4a13 023a bd02 2a3a 0419
    0x0000060: 045f 1302 3b5f 532c 1302 5613 024c 1302
    0x0000070: 3e13 023f 1904 1302 3b13 023a b602 5a19
    0x0000080: 0413 023b 32c0 0165 b700 062c 1302 4c13
    0x0000090: 023e 1302 3fb6 025e 2c13 024c 1302 3e13
    0x00000a0: 023f b602 6159 2c5f b602 6413 023a bd02
    0x00000b0: 2a3a 0419 045f 1302 3b5f 532c 1302 5613
    0x00000c0: 023d 1302 3e13 0265 1904 1302 3b13 023a
    0x00000d0: b602 5a19 0413 023b 32c0 00cd b700 072c
    0x00000e0: 1302 3d13 023e 1302 65b6 025e 2c13 023d
    0x00000f0: 1302 3e13 0265 b602 6159 2c5f b602 642c
    0x0000100: b602 68b1                              

        at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:73)
        at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:69)
        at org.springframework.boot.loader.Launcher.createArchive(Launcher.java:163)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:48)
        at org.springframework.boot.loader.JarLauncher.<init>(JarLauncher.java:48)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

**Comment by jon-bell** [comment]
@Instein98 @MirrorTaint is this repository monitored/maintained?
